### ISSUE TITLE
TypeError: Invalid query format when massive & pg-promise match demux-js-postgres module

### ISSUE THREAD

**Issue by jasonbert** [EOSIO/demux-js-postgres#78]
I'm receiving the `TypeError: Invalid query format.` error when my `init` migration is run. The setup prior to that has created tables in Postgres, so it's definitely able to do some queries.

![image](https://user-images.githubusercontent.com/2347572/63527305-bccd1080-c4f8-11e9-88d2-75eb644240fd.png)

```
PS C:\Work\bb\git\enterprise.demux> node src/index.js                                                                                                                                                                                                    
-- Starting Demux --

[ { migrations: [ [Migration] ], sequenceName: 'init' } ]
{"name":"demux","hostname":"localhost","pid":23216,"level":50,"err":{"message":"The proper initialization has not occurred. Failed to migrate the postgres database.","name":"NotInitializedError","stack":"NotInitializedError: The proper initialization has not occurred. Failed to migrate the postgres database.
    at MassiveActionHandler.<anonymous> (C:\\Work\\bb\\git\\enterprise.demux\\node_modules\\demux-postgres\\dist\\MassiveActionHandler.js:97:23)
	TypeError: Invalid query format.
    at Database.$query (C:\\Work\\bb\\git\\enterprise.demux\\node_modules\\pg-promise\\lib\\query.js:104:21)
    at Database.<anonymous> (C:\\Work\\bb\\git\\enterprise.demux\\node_modules\\pg-promise\\lib\\query.js:259:23)
    at config.$npm.connect.pool.then.db (C:\\Work\\bb\\git\\enterprise.demux\\node_modules\\pg-promise\\lib\\database.js:326:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"The proper initialization has not occurred. Failed to migrate the postgres database.","time":"2019-08-22T15:05:10.796Z","v":0}
{"name":"demux","hostname":"localhost","pid":23216,"level":30,"msg":"Indexing unexpectedly paused due to an error.","time":"2019-08-22T15:05:10.797Z","v":0}
```

index.js
```
console.log("");
console.log("-- Starting Demux --")
console.log("");

const massive = require('massive')
const { BaseActionWatcher } = require("demux")
const { MassiveActionHandler } = require("demux-postgres")
const { NodeosActionReader } = require("demux-eos")

const handlerVersions = require("./handlerVersions")
const migrationSequences = require("./migrationSequences")

console.log(migrationSequences);

const dbConfig = {
    host: '127.0.0.1',
    port: 5432,
    database: 'enterprise',
    user: 'postgres',
    password: 'docker'
}

massive(dbConfig).then((db) => {
    const actionReader = new NodeosActionReader("http://localhost:8888", 0)
    const actionHandler = new MassiveActionHandler(
        handlerVersions,
        db,
        "public",
        migrationSequences
    )
    const actionWatcher = new BaseActionWatcher(actionReader, actionHandler, 500)
    actionWatcher.watch()
})
```

migrationSequences/index.js
```
const { Migration } = require('demux-postgres')

const createTables = new Migration(
    "createTables", // name
    "public", // schema
    "migrationSequences/createTables.sql", // SQL file
)
  
module.exports = [{
    migrations: [createTables],
    sequenceName: "init"
}]
```

migrationSequences/createTables.sql
```
CREATE TABLE IF NOT EXISTS "${schema^}"."match_type" (
    "id" CHAR(64) PRIMARY KEY,
    "type" VARCHAR NOT NULL,
    "max_oppoonents" INTEGER NOT NULL
);
```

**Comment by vitaly-t** [comment]
The error means: pg-promise received a request from Massive.js that's not a real query, possibly a `null`, `undefined` or an empty string. In other words, at some point Massive.js failed to prepare a valid query, but still tried to execute it via pg-promise, which in turn threw the error.

**Comment by jasonbert** [comment]
Thanks for shedding some light on the potential issue, however I'm not sure where a query like that would be coming from?

**Comment by vitaly-t** [comment]
There it says in the error:
> node_modules\\demux-postgres\\dist\\MassiveActionHandler.js:97:23

It is doing there something that makes Massive.js execute an empty or missing query.

**Comment by jasonbert** [comment]
Still digging into this issue, but it appears to be because of the Cyan Audit SQL file that needs to be run. In the generic pg-promise `$query` function there's a check to see if the query is a string, but in this case the variable is an object.

![image](https://user-images.githubusercontent.com/2347572/63655132-18f39700-c77c-11e9-8675-96367d76424e.png)

![image](https://user-images.githubusercontent.com/2347572/63655165-a1723780-c77c-11e9-8dcc-3c00d3b0f2c8.png)

Looks like PG Promise isn't able to work out what to do with that query file and therefore doesn't change the `query` object in the actual query string.

**Comment by jasonbert** [comment]
Looks like this is a duplicate of issue https://github.com/EOSIO/demux-js-postgres/issues/67

**Comment by vitaly-t** [comment]
Yes, but from what I said above, you are looking at too deep. The issue is above pg-promise where such an invalid object gets passed in through Massive.js somehow, an object that does not represent a valid query. pg-promise correctly throwing on it is just the final consequence of it, as the higher layers fail to handle the situation.

**Comment by jasonbert** [comment]
Just to be clear, I haven't said pg-promise is the problem ;). And looking this deep led me to the same issue someone else faced.

**Comment by jasonbert** [comment]
Added comments to closed issue #67, but reopening this one as it's closed. I had to remove `.default` in the generated `index.js` file for the module. There's no `default` property when you do `require('massive')` as that exports the default and is then in `massive_1`. Obviously this isn't a fix and needs to be corrected in the TypeScript file https://github.com/EOSIO/demux-js-postgres/blob/develop/src/index.ts

![image](https://user-images.githubusercontent.com/2347572/63794079-0d79aa80-c8f9-11e9-9356-89e652034068.png)

**Comment by jasonbert** [comment]
Someone has kindly made a PR to fix this issue :)

https://github.com/EOSIO/demux-js-postgres/pull/83
