### ISSUE TITLE
Not able to run demux, getting an error

### ISSUE THREAD

**Issue by codemaster101** [EOSIO/demux-js-postgres#80]
Hi, while trying to run demux, I am getting an error. 

_The proper initialization has not occurred. Failed to migrate the postgres database._

The full error code is this:

{"name":"demux","hostname":"dev-eosio-1","pid":11836,"level":50,"err":{"message":"The proper initialization has not occurred. Failed to migrate the postgres database.","name":"NotInitializedError","stack":"NotInitializedError: The proper initialization has not occurred. Failed to migrate the postgres database.\n    at MassiveActionHandler.<anonymous> (/home/nodeos2/demux/node_modules/demux-postgres/dist/MassiveActionHandler.js:103:22)\nerror: deadlock detected\n    at Connection.parseE (/home/nodeos2/demux/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/home/nodeos2/demux/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/home/nodeos2/demux/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"},"msg":"The proper initialization has not occurred. Failed to migrate the postgres database.","time":"2019-09-05T07:42:30.220Z","v":0}
{"name":"demux","hostname":"dev-eosio-1","pid":11836,"level":30,"msg":"Indexing unexpectedly paused due to an error.","time":"2019-09-05T07:42:30.220Z","v":0}

After debugging through the node modules, I got a Promise { <pending> }, in Migration.js when calling  pgp.none(this.upQueryFile) in the up(pgp) function. 

The demux file I am running looks like this,

```

const { BaseActionWatcher } = require("demux")
const { MongoActionReader } = require("demux-eos")
const { MassiveActionHandler, massive } = require("demux-postgres")
const { Migration } = require("demux-postgres")

// See https://eosio.github.io/demux-js/ for info on Handler Versions, Updaters, and Effects
// const handlerVersions = require("./handlerVersions") // Import your handler versions
const handlerVersions = [
      {
        versionName: 'v1',
        deferUntilIrreversible: true,
      },
  ]

// See "Migrations" section above
//const migrationSequences = require("./migrationSequences")

const createTodoTable = new Migration(
  "table", // name
  "schema", // schema
  "create_todo_table.sql" // SQL file
)

const migrationSequences = [{
  migrations: [createTodoTable],
  sequenceName: "init"
}]

console.log(migrationSequences);

// See https://dmfay.github.io/massive-js/connecting.html for info on massive configuration
const dbConfig = {
  host: '127.0.0.1',
  port: 5432,
  database: 'postgres',
  user: 'user',
  password: 'pass'
}

massive(dbConfig).then((db) => {
 console.log("logging this",migrationSequences);
	const actionHandler = new MassiveActionHandler(
    handlerVersions,
    db,
    dbConfig.schema,
    migrationSequences
  )
	console.log("logging this",migrationSequences);
  const actionReader = new MongoActionReader({
    startAtBlock: 1234,              // startAtBlock: the first block relevant to our application
    onlyIrreversible: false,         // onlyIrreversible: whether or not to only process irreversible blocks
    dbName: "EOS2",                   // name of the database
    mongoEndpoint: "mongodb://user:pass@127.0.0.1:27017/EOS2",    // mongoEndpoint: the url of the mongodb instance
  })
  const actionWatcher = new BaseActionWatcher(actionReader, actionHandler, 500)
  actionReader.initialize().then(()=>
  actionWatcher.watch())
})
//async function migrateDatabase(db, payload) {
//  await db.migrate(payload.sequenceName)}

```

What is the reason for this error?

**Comment by codemaster101** [comment]
anyone?
